
## test login
POST http://localhost:8080/api/authentication/login HTTP/1.1
content-type: application/json

{
    "username": "david.lee@example.com",
    "password": "S003"
}
###

## test getAllProposals
GET http://localhost:8080/api/proposals HTTP/1.1
###

## test getDegrees
GET http://localhost:8080/api/degrees HTTP/1.1
###

## test getTeachers
GET http://localhost:8080/api/teachers HTTP/1.1
###


## test getProposalById
GET http://localhost:8080/api/proposals/P001 HTTP/1.1